version: '3.8'

services:
    foo:
        build:
            context: src/foo/
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        environment:
            - LIS_IP=0.0.0.0
            - LIS_PORT=4000
            - BAR_ENDPOINT=bar:4001

    bar:
        build:
            context: src/bar/
            dockerfile: Dockerfile
        ports: 
            - "4001:4001"
        environment:
            - LIS_IP=0.0.0.0
            - LIS_PORT=4001

    math:
        build:
            context: src/maths
            dockerfile: Dockerfile
        ports: 
            - "4002:4002"
        environment:
            - LIS_IP=0.0.0.0
            - LIS_PORT=4002

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
