version: '3.8'

services:
    foo:
        build:
            context: foo/
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        environment:
            - LIS_IP=0.0.0.0
            - LIS_PORT=4000
            - BAR_ENDPOINT=bar:4001

    bar:
        build:
            context: bar/
            dockerfile: Dockerfile
        ports: 
            - "4001:4001"
        environment:
            - LIS_IP=0.0.0.0
            - LIS_PORT=4001