name: push-dhub

on:
  push:
    branches:
      - main
    tags:
      - latest

env:
  IMAGE_NAME_FOO: foo
  IMAGE_NAME_BAR: bar
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
  DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN}}

jobs:

  # foo
  push_foo:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Build image
        run: docker build -t ${IMAGE_NAME_FOO}:latest foo/
      
      - name: Docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push image
        run: docker push ${DOCKER_USER}/foobar-first
        

  # foo
  push_bar:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}

      - name: Build image
        run: docker build -t ${IMAGE_NAME_BAR}:latest bar/
      
      - name: Docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push image
        run: docker push ${DOCKER_USER}/foobar-first